# Generated by Django 4.1.4 on 2023-01-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsgo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='description',
            field=models.TextField(default=None, max_length=360),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=None, max_length=360),
        ),
    ]
